- 👋 Olá, meu nome é Mateus.
- 👀 Estou interessado em sempre aprender coisas novas na área da Tecnologia da Informação ...
- 🌱 Atualmente estou aprendendo HTML5/CSS3/JS porém procurando me aprimorar em Python ...
- 💞️ Procuro uma oportunidade de mostrar minha vontade de aprender e também ensinar outras pessoas ...
- 📫 Você pode me encontrar pelo meu Linkedin: @mattfelipe...
